export const SIGN_UP_SUCCESS_MODAL = "SIGN_UP_SUCCESS_MODAL";
export const LOGIN_RESET_PASSWORD_MODAL = "LOGIN_RESET_PASSWORD_MODAL";
export const SUCCESS_RESET_PASSWORD_MODAL = "SUCCESS_RESERT_PASSWORD_MODAL";
export const MENU = "MENU";